[precedente configurazione...]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${COMPOSE_PROJECT_NAME:-digitaldept}_phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - PMA_ARBITRARY=0
      - PMA_ABSOLUTE_URI=https://${DOMAIN}/phpmyadmin/
      - UPLOAD_LIMIT=64M
      - MEMORY_LIMIT=256M
      - MAX_EXECUTION_TIME=600
      - PMA_MAX_ROWS=100
    volumes:
      - ./docker/phpmyadmin/config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    networks:
      - backend
