name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Docker Compose
        run: |
          docker-compose config -q
          
      - name: Build Docker images
        run: docker-compose build

      - name: Test containers
        run: |
          docker-compose up -d
          sleep 10
          docker-compose ps
          docker-compose logs
          docker-compose down

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Docker Compose Security Check
        run: |
          docker-compose config | grep -i password
          docker-compose config | grep -i secret

  deploy:
    needs: [test, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy notification
        run: |
          echo "Deployment would happen here"
          # Add actual deployment steps when ready
